version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: bm-ai-qdrant-prod
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bm-ai-network
    restart: unless-stopped

  # FastAPI Backend (Production)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bm-ai-backend-prod
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_URL=
      - QDRANT_API_KEY=
    volumes:
      - ./uploads:/tmp/uploads  # For file uploads
      # Note: Source code is NOT mounted in production
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bm-ai-network
    restart: unless-stopped
    # Production optimizations
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  qdrant_storage:
    driver: local

networks:
  bm-ai-network:
    driver: bridge
